apiVersion: v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu:21.10
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
